import express from "express";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import cookieParser from "cookie-parser";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";
import pg from "pg";
import dotenv from "dotenv";
import path from "node:path";
import crypto from "node:crypto";
import {fileURLToPath} from "node:url";

dotenv.config();
const {Pool}=pg;
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),app=express(),PORT=Number(process.env.PORT||3000);
if(!process.env.JWT_SECRET) throw Error("JWT_SECRET required");
if(!process.env.DATABASE_URL) throw Error("DATABASE_URL required");
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL!="false"?{rejectUnauthorized:false}:false,max:Number(process.env.DB_POOL_MAX||5)});
const q=(text,params=[])=>pool.query(text,params);
await q(`
CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS downloads(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,description TEXT,url TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'General',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS categories(id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,description TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS login_events(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,email TEXT,success BOOLEAN NOT NULL,ip TEXT,user_agent TEXT,device TEXT,browser TEXT,os TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,ip TEXT,user_agent TEXT,device TEXT,browser TEXT,os TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),revoked BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS audit_logs(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,action TEXT NOT NULL,details TEXT,ip TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
`);
for(const c of [["General","General downloads"],["Tools","Utilities and tools"],["Resources","Resources"]]) await q("INSERT INTO categories(name,description) VALUES($1,$2) ON CONFLICT(name) DO NOTHING",c);
if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD){const x=await q("SELECT id FROM users WHERE email=$1",[process.env.ADMIN_EMAIL.toLowerCase()]);if(!x.rowCount){const h=await bcrypt.hash(process.env.ADMIN_PASSWORD,12);await q("INSERT INTO users(email,password_hash,role) VALUES($1,$2,'admin')",[process.env.ADMIN_EMAIL.toLowerCase(),h])}}
app.set("trust proxy",process.env.TRUST_PROXY==="true");
app.use(helmet());app.use(express.json({limit:"100kb"}));app.use(cookieParser());app.use("/api/auth",rateLimit({windowMs:15*60*1000,limit:20}));
const ip=req=>String(req.ip||req.socket.remoteAddress||"").replace("::ffff","");
function parseAgent(ua=""){const s=ua.toLowerCase();const device=/mobile|android|iphone|ipod/.test(s)?"Mobile":/ipad|tablet/.test(s)?"Tablet":"Desktop";const browser=/edg\//.test(s)?"Edge":/chrome\//.test(s)?"Chrome":/firefox\//.test(s)?"Firefox":/safari\//.test(s)&&!/chrome/.test(s)?"Safari":/opr\//.test(s)?"Opera":"Unknown";const os=/android/.test(s)?"Android":/iphone|ipad|ios/.test(s)?"iOS":/windows/.test(s)?"Windows":/mac os/.test(s)?"macOS":/linux/.test(s)?"Linux":"Unknown";return{device,browser,os}}
const sign=(u,sid)=>jwt.sign({sub:u.id,role:u.role,sid},process.env.JWT_SECRET,{expiresIn:"2h",issuer:"darkside"});
async function auth(req,res,next){try{const t=req.cookies.darkside_session;if(!t)return res.status(401).json({error:"Authentication required"});const p=jwt.verify(t,process.env.JWT_SECRET,{issuer:"darkside"}),s=(await q("SELECT * FROM sessions WHERE id=$1 AND user_id=$2 AND revoked=FALSE",[p.sid,p.sub])).rows[0];if(!s)return res.status(401).json({error:"Session revoked"});await q("UPDATE sessions SET last_seen=NOW() WHERE id=$1",[s.id]);req.user=p;next()}catch{res.status(401).json({error:"Invalid or expired session"})}}
function admin(req,res,next){if(req.user?.role!=="admin")return res.status(403).json({error:"Forbidden"});next()}
async function audit(id,a,details,ipaddr){await q("INSERT INTO audit_logs(user_id,action,details,ip) VALUES($1,$2,$3,$4)",[id,a,details||"",ipaddr])}
app.post("/api/auth/register",async(req,res)=>{try{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<10)return res.status(400).json({error:"Invalid email or password"});if((await q("SELECT id FROM users WHERE email=$1",[email])).rowCount)return res.status(409).json({error:"Account already exists"});const h=await bcrypt.hash(password,12),r=await q("INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id",[email,h]);await audit(r.rows[0].id,"ACCOUNT_CREATED",email,ip(req));res.status(201).json({success:true})}catch(e){console.error(e);res.status(500).json({error:"Server error"})}});
app.post("/api/auth/login",async(req,res)=>{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),u=(await q("SELECT id,email,password_hash,role,status FROM users WHERE email=$1",[email])).rows[0],a=parseAgent(req.get("user-agent")||""),ipaddr=ip(req);if(!u||!(await bcrypt.compare(password,u.password_hash))){await q("INSERT INTO login_events(email,success,ip,user_agent,device,browser,os) VALUES($1,FALSE,$2,$3,$4,$5,$6)",[email,ipaddr,req.get("user-agent")||"",a.device,a.browser,a.os]);return res.status(401).json({error:"Invalid credentials"})}if(u.status!=="active")return res.status(403).json({error:"Account disabled"});const sid=crypto.randomUUID();await q("INSERT INTO sessions(id,user_id,ip,user_agent,device,browser,os) VALUES($1,$2,$3,$4,$5,$6,$7)",[sid,u.id,ipaddr,req.get("user-agent")||"",a.device,a.browser,a.os]);await q("INSERT INTO login_events(user_id,email,success,ip,user_agent,device,browser,os) VALUES($1,$2,TRUE,$3,$4,$5,$6,$7)",[u.id,u.email,ipaddr,req.get("user-agent")||"",a.device,a.browser,a.os]);await audit(u.id,"LOGIN",`${a.device}/${a.browser}/${a.os}`,ipaddr);res.cookie("darkside_session",sign(u,sid),{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",maxAge:7200000,path:"/"});res.json({success:true,user:{id:u.id,email:u.email,role:u.role}})});
app.post("/api/auth/logout",auth,async(req,res)=>{await q("UPDATE sessions SET revoked=TRUE WHERE id=$1",[req.user.sid]);await audit(req.user.sub,"LOGOUT","",ip(req));res.clearCookie("darkside_session",{httpOnly:true,sameSite:"lax",path:"/"});res.json({success:true})});
app.get("/api/auth/me",auth,async(req,res)=>res.json((await q("SELECT id,email,role,status,created_at FROM users WHERE id=$1",[req.user.sub])).rows[0]||{}));
app.get("/api/downloads",auth,async(req,res)=>res.json((await q("SELECT * FROM downloads ORDER BY id DESC")).rows));
app.post("/api/downloads",auth,admin,async(req,res)=>{const n=String(req.body.name||"").trim(),d=String(req.body.description||"").trim(),u=String(req.body.url||"").trim(),c=String(req.body.category||"General").trim();if(!n||!u)return res.status(400).json({error:"Name and URL required"});const r=await q("INSERT INTO downloads(name,description,url,category) VALUES($1,$2,$3,$4) RETURNING id",[n,d,u,c]);await audit(req.user.sub,"DOWNLOAD_CREATED",n,ip(req));res.status(201).json({id:r.rows[0].id})});
const normalize=a=>Array.isArray(a)?a.map(c=>({name:String(c.name||""),value:String(c.value||""),path:String(c.path||"/"),domain:String(c.domain||""),secure:Boolean(c.secure),httpOnly:Boolean(c.httpOnly)})):null;
app.post("/api/tools/cookies-to-json",auth,(req,res)=>{const c=normalize(req.body.cookies);if(!c)return res.status(400).json({error:"cookies must be an array"});res.json({cookies:c})});app.post("/api/tools/json-to-cookies",auth,(req,res)=>{const c=normalize(req.body.cookies);if(!c)return res.status(400).json({error:"cookies must be an array"});res.json({cookies:c})});
app.get("/api/admin/stats",auth,admin,async(req,res)=>{const vals=await Promise.all(["users","downloads","audit_logs","login_events","categories"].map(t=>q(`SELECT COUNT(*)::int c FROM ${t}`)));const active=await q("SELECT COUNT(*)::int c FROM sessions WHERE revoked=FALSE");res.json({users:vals[0].rows[0].c,downloads:vals[1].rows[0].c,logs:vals[2].rows[0].c,logins:vals[3].rows[0].c,activeSessions:active.rows[0].c,categories:vals[4].rows[0].c})});
app.get("/api/admin/users",auth,admin,async(req,res)=>res.json((await q("SELECT id,email,role,status,created_at FROM users ORDER BY id DESC")).rows));
app.patch("/api/admin/users/:id",auth,admin,async(req,res)=>{const role=req.body.role,status=req.body.status;if(role&&!['user','moderator','admin'].includes(role))return res.status(400).json({error:"Invalid role"});if(status&&!['active','disabled'].includes(status))return res.status(400).json({error:"Invalid status"});const u=(await q("SELECT id,email FROM users WHERE id=$1",[req.params.id])).rows[0];if(!u)return res.status(404).json({error:"User not found"});if(role)await q("UPDATE users SET role=$1 WHERE id=$2",[role,u.id]);if(status)await q("UPDATE users SET status=$1 WHERE id=$2",[status,u.id]);await audit(req.user.sub,"USER_UPDATED",`${u.email}:${role||''}:${status||''}`,ip(req));res.json({success:true})});
app.get("/api/admin/login-events",auth,admin,async(req,res)=>res.json((await q("SELECT * FROM login_events ORDER BY id DESC LIMIT 200")).rows));
app.get("/api/admin/sessions",auth,admin,async(req,res)=>res.json((await q("SELECT s.id,s.user_id,u.email,s.ip,s.device,s.browser,s.os,s.created_at,s.last_seen,s.revoked FROM sessions s JOIN users u ON u.id=s.user_id ORDER BY s.last_seen DESC LIMIT 200")).rows));
app.delete("/api/admin/sessions/:id",auth,admin,async(req,res)=>{await q("UPDATE sessions SET revoked=TRUE WHERE id=$1",[req.params.id]);await audit(req.user.sub,"SESSION_REVOKED",req.params.id,ip(req));res.json({success:true})});
app.get("/api/admin/categories",auth,admin,async(req,res)=>res.json((await q("SELECT * FROM categories ORDER BY name")).rows));
app.post("/api/admin/categories",auth,admin,async(req,res)=>{const n=String(req.body.name||"").trim(),d=String(req.body.description||"").trim();if(!n)return res.status(400).json({error:"Name required"});try{const r=await q("INSERT INTO categories(name,description) VALUES($1,$2) RETURNING id",[n,d]);await audit(req.user.sub,"CATEGORY_CREATED",n,ip(req));res.status(201).json({id:r.rows[0].id})}catch{res.status(409).json({error:"Category already exists"})}});
app.delete("/api/admin/categories/:id",auth,admin,async(req,res)=>{await q("DELETE FROM categories WHERE id=$1",[req.params.id]);await audit(req.user.sub,"CATEGORY_DELETED",req.params.id,ip(req));res.json({success:true})});
app.get("/api/admin/audit",auth,admin,async(req,res)=>res.json((await q("SELECT a.*,u.email FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 300")).rows));
app.get("/api/admin/settings",auth,admin,async(req,res)=>res.json(Object.fromEntries((await q("SELECT key,value FROM settings")).rows.map(x=>[x.key,x.value]))));
app.put("/api/admin/settings",auth,admin,async(req,res)=>{for(const [k,v] of Object.entries(req.body||{})){if(!/^[a-zA-Z0-9_.-]{1,80}$/.test(k))continue;await q("INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[k,String(v)])}await audit(req.user.sub,"SETTINGS_UPDATED",JSON.stringify(req.body),ip(req));res.json({success:true})});
app.get("/api/admin/export",auth,admin,async(req,res)=>{const [users,categories,downloads,login_events,audit_logs]=await Promise.all([q("SELECT id,email,role,status,created_at FROM users"),q("SELECT * FROM categories"),q("SELECT * FROM downloads"),q("SELECT * FROM login_events"),q("SELECT * FROM audit_logs")]);res.setHeader("Content-Disposition","attachment; filename=darkside-export.json");res.json({users:users.rows,categories:categories.rows,downloads:downloads.rows,login_events:login_events.rows,audit_logs:audit_logs.rows})});
app.use(express.static(path.join(__dirname,"../public")));
app.listen(PORT,()=>console.log(`DARKSIDE Risssa running on ${PORT}`));
process.on("SIGTERM",async()=>{await pool.end();process.exit(0)});
